
package formularios;

import classes.Dados;
import classes.Opcoes;
import classes.Ultilidades;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


public class frmFatura extends javax.swing.JInternalFrame {
     private Dados msDados;
     private DefaultTableModel mTabela; 
    
    public void setDados(Dados msDados){
        this.msDados = msDados;
    }    
    public frmFatura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtdata = new javax.swing.JTextField();
        cmbporduto = new javax.swing.JComboBox();
        cmbcliente = new javax.swing.JComboBox();
        txtqunatidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldetalhes = new javax.swing.JTable();
        btnpesqcliente = new javax.swing.JButton();
        btnpesqproduto = new javax.swing.JButton();
        btnadicionar = new javax.swing.JButton();
        btndeletar = new javax.swing.JButton();
        btndeletartodos = new javax.swing.JButton();
        btnsalvar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtquant = new javax.swing.JTextField();
        txtvalor = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Data :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Nome :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Produto :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Quantidade :");

        txtdata.setEnabled(false);

        tbldetalhes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbldetalhes);

        btnpesqcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2203511_find_glass_look_magnify_search_icon (1).png"))); // NOI18N
        btnpesqcliente.setToolTipText("Pesquisar Cliente");
        btnpesqcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesqclienteActionPerformed(evt);
            }
        });

        btnpesqproduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2203511_find_glass_look_magnify_search_icon (1)_1.png"))); // NOI18N
        btnpesqproduto.setToolTipText("Pesquisar Produto");
        btnpesqproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesqprodutoActionPerformed(evt);
            }
        });

        btnadicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/134224_add_plus_new_icon (1).png"))); // NOI18N
        btnadicionar.setToolTipText("adcionar produto");
        btnadicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadicionarActionPerformed(evt);
            }
        });

        btndeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/430088_circle_close_delete_remove_icon (1).png"))); // NOI18N
        btndeletar.setToolTipText("deletar produto");
        btndeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletarActionPerformed(evt);
            }
        });

        btndeletartodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/185090_delete_garbage_icon (1).png"))); // NOI18N
        btndeletartodos.setToolTipText("deletar todos os produtos");
        btndeletartodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletartodosActionPerformed(evt);
            }
        });

        btnsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/285657_floppy_guardar_save_icon (1).png"))); // NOI18N
        btnsalvar.setToolTipText("salvar venda");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/49617_report_sales_icon (1).png"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setText("Total");

        txtquant.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtquant.setEnabled(false);

        txtvalor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtvalor.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnadicionar)
                        .addGap(18, 18, 18)
                        .addComponent(btndeletar)
                        .addGap(18, 18, 18)
                        .addComponent(btndeletartodos)
                        .addGap(18, 18, 18)
                        .addComponent(btnsalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtdata)
                            .addComponent(cmbcliente, 0, 131, Short.MAX_VALUE)
                            .addComponent(cmbporduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtqunatidade))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnpesqcliente)
                                    .addComponent(btnpesqproduto)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(jLabel5))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(39, 39, 39)
                        .addComponent(txtquant, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpesqcliente))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbporduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpesqproduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtqunatidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadicionar)
                    .addComponent(btndeletar)
                    .addComponent(btndeletartodos)
                    .addComponent(btnsalvar))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtquant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        Opcoes opc = new Opcoes("alessandro.codogno18gmail.com","Selecione um cliente");
        cmbcliente.addItem(opc);
        for(int i = 0; i<msDados.numeroClientes(); i++){
        opc = new Opcoes(
        msDados.getClientes()[i].getIdCliente(),
        msDados.getClientes()[i].getNome()+""+
        msDados.getClientes()[i].getSNome());
        cmbcliente.addItem(opc);
        
    }
        
        opc = new Opcoes("alessandro.codogno18gmail.com", "Selecione um produto");
        cmbporduto.addItem(opc);
        for(int i = 0; i<msDados.numeroProdutos(); i++){
        opc = new Opcoes(
        msDados.getProdutos()[i].getIdProduto(),
        msDados.getProdutos()[i].getDescricao());
        cmbporduto.addItem(opc);
        
    }
        
        
        
        txtdata.setText(Ultilidades.formatDate(new Date()));
        txtquant.setText("0");
        txtvalor.setText("0");
        preencherTabela();
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnadicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadicionarActionPerformed
        if(cmbporduto.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(rootPane, "Favor selecionar um produto");
            cmbporduto.requestFocusInWindow();
            return; 
        }
        if(txtqunatidade.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Favor selecionar um quantidade");
            txtqunatidade.requestFocusInWindow();
            return; 
        }
        
        if(!Ultilidades.isNumeric(txtqunatidade.getText())){
            JOptionPane.showMessageDialog(rootPane, "Favor digitar somente numeros");
            txtqunatidade.setText("");
            txtqunatidade.requestFocusInWindow();
            return;
        }
         
         int qunatidade = Integer.parseInt(txtqunatidade.getText());
            if(qunatidade <= 0){
            JOptionPane.showMessageDialog(rootPane, "Favor digitar um numero acima de zero");
            txtqunatidade.setText("");
            txtqunatidade.requestFocusInWindow();
            return;
        }
            
           
            
        int pos = msDados.posicaoProduto(((Opcoes)cmbporduto.getSelectedItem()).getValor());
        
        String registro[] = new String[5];
        registro[0]=msDados.getProdutos()[pos].getIdProduto();
        registro[1]=msDados.getProdutos()[pos].getDescricao();
        registro[2]=""+ msDados.getProdutos()[pos].getPreco();
        registro[3]=""+ qunatidade;
        registro[4]=""+ (qunatidade*msDados.getProdutos()[pos].getPreco());
        mTabela.addRow(registro);
        
        cmbporduto.setSelectedIndex(0);
        txtqunatidade.setText("");
        cmbporduto.requestFocusInWindow();
        totais();
    }//GEN-LAST:event_btnadicionarActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        if(cmbcliente.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(rootPane, "Favor selecionar um cliente");
            cmbcliente.requestFocusInWindow();
            return;
        }                              
        int totalquant = new Integer(txtquant.getText());
        if(totalquant==0){
            JOptionPane.showMessageDialog(rootPane, "Favor selecionar os produtos para realizar sua compra");
            cmbporduto.requestFocusInWindow();
            return;
        }
        int resposta = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja realizar essa venda");
        if(resposta  != 0){
        return;
        }
        
        int numFatura = msDados.getNumeroFatura()+1;
        FileWriter fw = null;
        PrintWriter pw = null;
        try {
            fw = new FileWriter("Data/fatura.txt",true);
            pw = new PrintWriter(fw);

        String aux = "1|"
                +numFatura +"|"
                +((Opcoes)cmbcliente.getSelectedItem()).getValor()+"|"
                +((Opcoes)cmbcliente.getSelectedItem()).getDescricao()+"|"
                +txtdata.getText();
        
        pw.println(aux);
        
        int num = tbldetalhes.getRowCount();
        
        for(int i =0; i < num; i++){
            aux ="2|" 
                    + Ultilidades.objectToString(tbldetalhes.getValueAt(i, 0))+"|"
                    + Ultilidades.objectToString(tbldetalhes.getValueAt(i, 1))+"|"
                    + Ultilidades.objectToString(tbldetalhes.getValueAt(i, 2))+"|"
                    + Ultilidades.objectToString(tbldetalhes.getValueAt(i, 3))+"|"
                    + Ultilidades.objectToString(tbldetalhes.getValueAt(i, 4));
                    
             pw.println(aux);    
        }
                
        } catch (Exception e1) {
           e1.printStackTrace();
        }finally{
           try {
            if(fw != null){
                fw.close();
            }
        } catch (Exception e2) {
            e2.printStackTrace();
        }
      }
     JOptionPane.showMessageDialog(rootPane,
             "Venda:"+numFatura+"Venda realizada com sucesso");
             msDados.setNumeroFatura(numFatura);
             cmbcliente.setSelectedIndex(0);
             limpartabela();
             totais();
             cmbcliente.requestFocusInWindow();
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btndeletartodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletartodosActionPerformed
        int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente deletar esta venda  ?");
        if(resposta  !=0){
            return;
        }
        limpartabela();
        totais();
    }//GEN-LAST:event_btndeletartodosActionPerformed

    private void btndeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletarActionPerformed
         if(cmbporduto.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(rootPane, "Favor selecionar um produto");
            cmbporduto.requestFocusInWindow();
            return; 
        }
         
        try {
        DefaultTableModel modelo =(DefaultTableModel)tbldetalhes.getModel();
        int Linha = tbldetalhes.getRowCount();
        for(int i = 0; Linha > i; i++){
            String idtabela = Ultilidades.objectToString(tbldetalhes.getValueAt(i, 0));
            String idCombo = ((Opcoes)cmbporduto.getSelectedItem()).getValor();
            if(idtabela.equals(idCombo)){
            modelo.removeRow(i);
            totais();
            return;
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
    } 
         
         
    }//GEN-LAST:event_btndeletarActionPerformed

    private void btnpesqclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesqclienteActionPerformed
        frmPesqCliente mPesqCliente = new frmPesqCliente(null, closable);
        mPesqCliente.setDados(msDados);
        mPesqCliente.setLocationRelativeTo(null);
        mPesqCliente.setVisible(true);
        String rta = mPesqCliente.getResposta();
        if(rta.equals("")){
            return;
        }
        for(int i =0; i< cmbcliente.getItemCount();i++){
        if(((Opcoes)cmbcliente.getItemAt(i)).getValor().equals(rta)){
          cmbcliente.setSelectedIndex(i);
          return;
        }
      } 
    }//GEN-LAST:event_btnpesqclienteActionPerformed

    private void btnpesqprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesqprodutoActionPerformed
        frmPesqProdutos mPesqProdutos = new frmPesqProdutos(null, closable);
        mPesqProdutos.setDados(msDados);
        mPesqProdutos.setLocationRelativeTo(null);
        mPesqProdutos.setVisible(true);
        String rta = mPesqProdutos.getResposta();
        if(rta.equals("")){
            return;
        }
        for(int i =0; i< cmbporduto.getItemCount();i++){
        if(((Opcoes)cmbporduto.getItemAt(i)).getValor().equals(rta)){
          cmbporduto.setSelectedIndex(i);
          return;
        }
      } 
    }//GEN-LAST:event_btnpesqprodutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadicionar;
    private javax.swing.JButton btndeletar;
    private javax.swing.JButton btndeletartodos;
    private javax.swing.JButton btnpesqcliente;
    private javax.swing.JButton btnpesqproduto;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JComboBox cmbcliente;
    private javax.swing.JComboBox cmbporduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbldetalhes;
    private javax.swing.JTextField txtdata;
    private javax.swing.JTextField txtquant;
    private javax.swing.JTextField txtqunatidade;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables

private void preencherTabela(){
        String titulos[] = {"ID Prod","Desc","Preco","qtda","valor"};
        String registro[] = new String[5];
        mTabela = new DefaultTableModel(null,titulos);
        tbldetalhes.setModel(mTabela);
        
        
        DefaultTableCellRenderer dtcr = new DefaultTableCellRenderer();
        dtcr.setHorizontalAlignment(SwingConstants.RIGHT);
        tbldetalhes.getColumnModel().getColumn(2).setCellRenderer(dtcr);
        tbldetalhes.getColumnModel().getColumn(3).setCellRenderer(dtcr);
        tbldetalhes.getColumnModel().getColumn(4).setCellRenderer(dtcr);
        }
private void totais(){
    int num = tbldetalhes.getRowCount();
    int somQuant = 0, somVal = 0;
    for(int i =0; i < num; i++){
        somQuant += Ultilidades.objectToInt(tbldetalhes.getValueAt(i, 3));
        somVal += Ultilidades.objectToInt(tbldetalhes.getValueAt(i, 4));
               
    }
    txtquant.setText(""+somQuant);
    txtvalor.setText(""+somVal);
    }

public void limpartabela(){
    try {
        DefaultTableModel modelo =(DefaultTableModel)tbldetalhes.getModel();
        int Linha = tbldetalhes.getRowCount();
        for(int i = 0; Linha > i; i++){
            modelo.removeRow(0);
            
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    }

