
package formularios;

import classes.Dados;
import classes.Ultilidades;
import javax.swing.table.DefaultTableModel;



public class frmPesqCliente extends javax.swing.JDialog {
     private Dados msDados;
     private DefaultTableModel mTabela; 
     private String  resposta = "";
     
    
public void setDados(Dados msDados){
        this.msDados = msDados;
    } 

public String  getResposta(){
    return resposta;
}
    
 private void preencherTabela(){
        String titulos[] = {"ID Cliente","Nome","S_Nome"};
        String registro[] = new String[3];
        mTabela = new DefaultTableModel(null,titulos);
        if(txtpesqcli.getText().equals("")){
            for(int i = 0;i < msDados.numeroClientes();i++){
                
                registro[0]=msDados.getClientes()[i].getIdCliente();
                registro[1]= msDados.getClientes()[i].getNome();
                registro[2]=msDados.getClientes()[i].getSNome();
                mTabela.addRow(registro);
        }
            tblTabela.setModel(mTabela);
            return; 
        }
        if(radionome.isSelected()){
            for(int i = 0;i < msDados.numeroClientes();i++){ 
               if(msDados.getClientes()[i].getNome().startsWith(txtpesqcli.getText())){
               registro[0]=msDados.getClientes()[i].getIdCliente();
               registro[1]= msDados.getClientes()[i].getNome();
               registro[2]=msDados.getClientes()[i].getSNome();
               mTabela.addRow(registro);
                }
            }
            tblTabela.setModel(mTabela);
            return; 
        }
        
        if(radiosnome.isSelected()){
            for(int i = 0;i < msDados.numeroClientes();i++){ 
               if(msDados.getClientes()[i].getSNome().startsWith(txtpesqcli.getText())){
               registro[0]=msDados.getClientes()[i].getIdCliente();
               registro[1]= msDados.getClientes()[i].getNome();
               registro[2]=msDados.getClientes()[i].getSNome();
               mTabela.addRow(registro);
                }
            }
            tblTabela.setModel(mTabela);
            return; 
        }
        
        if(radioid.isSelected()){
            for(int i = 0;i < msDados.numeroClientes();i++){ 
               if(msDados.getClientes()[i].getIdCliente().startsWith(txtpesqcli.getText())){
               registro[0]=msDados.getClientes()[i].getIdCliente();
               registro[1]= msDados.getClientes()[i].getNome();
               registro[2]=msDados.getClientes()[i].getSNome();
               mTabela.addRow(registro);
                }
            }
            tblTabela.setModel(mTabela);
        }
    }
   

    
    public frmPesqCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        bgtipopesq.add(radioid);
        bgtipopesq.add(radionome);
        bgtipopesq.add(radiosnome);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgtipopesq = new javax.swing.ButtonGroup();
        radioid = new javax.swing.JRadioButton();
        radionome = new javax.swing.JRadioButton();
        radiosnome = new javax.swing.JRadioButton();
        txtpesqcli = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabela = new javax.swing.JTable();
        btnpesqcli = new javax.swing.JButton();
        btnpesqSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulario de Pesquisa de Cliente :");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        radioid.setSelected(true);
        radioid.setText("ID_Cliente");
        radioid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioidActionPerformed(evt);
            }
        });

        radionome.setText("Nome Cliente");
        radionome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radionomeActionPerformed(evt);
            }
        });

        radiosnome.setText("S_Nome Cliente");
        radiosnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiosnomeActionPerformed(evt);
            }
        });

        txtpesqcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesqcliActionPerformed(evt);
            }
        });

        tblTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTabela);

        btnpesqcli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2203511_find_glass_look_magnify_search_icon (1).png"))); // NOI18N
        btnpesqcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesqcliActionPerformed(evt);
            }
        });

        btnpesqSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/430088_circle_close_delete_remove_icon (1).png"))); // NOI18N
        btnpesqSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesqSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(radionome)
                        .addGap(66, 66, 66)
                        .addComponent(radiosnome))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtpesqcli))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnpesqcli)
                .addGap(18, 18, 18)
                .addComponent(btnpesqSair)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioid)
                    .addComponent(radionome)
                    .addComponent(radiosnome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtpesqcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpesqcli)
                    .addComponent(btnpesqSair))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpesqSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesqSairActionPerformed
        resposta="";
        dispose();
    }//GEN-LAST:event_btnpesqSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        preencherTabela();
        txtpesqcli.requestFocusInWindow();
    }//GEN-LAST:event_formWindowOpened

    private void radionomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radionomeActionPerformed
        txtpesqcli.setText("");
        txtpesqcli.requestFocusInWindow();
        preencherTabela();
    }//GEN-LAST:event_radionomeActionPerformed

    private void radiosnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiosnomeActionPerformed
        txtpesqcli.setText("");
        txtpesqcli.requestFocusInWindow();
        preencherTabela();
    }//GEN-LAST:event_radiosnomeActionPerformed

    private void radioidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioidActionPerformed
        txtpesqcli.setText("");
        txtpesqcli.requestFocusInWindow();
        preencherTabela();
    }//GEN-LAST:event_radioidActionPerformed

    private void txtpesqcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesqcliActionPerformed
        preencherTabela();
    }//GEN-LAST:event_txtpesqcliActionPerformed

    private void btnpesqcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesqcliActionPerformed
        int num = tblTabela.getRowCount();
        if(num==0){
            resposta="";
            dispose();  
            return;
        }
         for(int i =0; i < num; i++){
            if(tblTabela.isRowSelected(i)){
            resposta = Ultilidades.objectToString(tblTabela.getValueAt(i, 0));
            dispose();  
            return;
            
            }
        }
         resposta = Ultilidades.objectToString(tblTabela.getValueAt(0, 0));
         dispose();  
    }//GEN-LAST:event_btnpesqcliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPesqCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPesqCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPesqCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPesqCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmPesqCliente dialog = new frmPesqCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgtipopesq;
    private javax.swing.JButton btnpesqSair;
    private javax.swing.JButton btnpesqcli;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioid;
    private javax.swing.JRadioButton radionome;
    private javax.swing.JRadioButton radiosnome;
    private javax.swing.JTable tblTabela;
    private javax.swing.JTextField txtpesqcli;
    // End of variables declaration//GEN-END:variables
}
