
package formularios;

import classes.Dados;
import classes.Ultilidades;
import javax.swing.table.DefaultTableModel;



public class frmPesqProdutos extends javax.swing.JDialog {
     private Dados msDados;
     private DefaultTableModel mTabela; 
     private String  resposta = "";
     
    
public void setDados(Dados msDados){
        this.msDados = msDados;
    } 

public String  getResposta(){
    return resposta;
}
    
 private void preencherTabela(){
        String titulos[] = {"ID Produto","Descricao"};
        String registro[] = new String[2];
        mTabela = new DefaultTableModel(null,titulos);
        if(txtpesqprod.getText().equals("")){
            for(int i = 0;i < msDados.numeroProdutos();i++){
                
                registro[0]=msDados.getProdutos()[i].getIdProduto();
                registro[1]= msDados.getProdutos()[i].getDescricao();
                mTabela.addRow(registro);
        }
            tblTabela.setModel(mTabela);
            return; 
        }
        if(radiodesdricaoproduto.isSelected()){
            for(int i = 0;i < msDados.numeroProdutos();i++){ 
               if(msDados.getProdutos()[i].getDescricao().startsWith(txtpesqprod.getText())){
               registro[0]=msDados.getProdutos()[i].getIdProduto();
               registro[1]= msDados.getProdutos()[i].getDescricao();
               mTabela.addRow(registro);
                }
            }
            tblTabela.setModel(mTabela);
            return; 
        }
        if(radioidprod.isSelected()){
            for(int i = 0;i < msDados.numeroProdutos();i++){ 
               if(msDados.getProdutos()[i].getIdProduto().startsWith(txtpesqprod.getText())){
               registro[0]=msDados.getProdutos()[i].getIdProduto();
               registro[1]= msDados.getProdutos()[i].getDescricao();
               mTabela.addRow(registro);
                }
            }
            tblTabela.setModel(mTabela);
        }
    }
   

    
    public frmPesqProdutos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        bgtipopesq.add(radioidprod);
        bgtipopesq.add(radiodesdricaoproduto);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgtipopesq = new javax.swing.ButtonGroup();
        radioidprod = new javax.swing.JRadioButton();
        radiodesdricaoproduto = new javax.swing.JRadioButton();
        txtpesqprod = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabela = new javax.swing.JTable();
        btnpesqcli = new javax.swing.JButton();
        btnpesqSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulario de Pesquisa de Produto :");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        radioidprod.setSelected(true);
        radioidprod.setText("ID_Produto");
        radioidprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioidprodActionPerformed(evt);
            }
        });

        radiodesdricaoproduto.setText("Descrição");
        radiodesdricaoproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiodesdricaoprodutoActionPerformed(evt);
            }
        });

        txtpesqprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesqprodActionPerformed(evt);
            }
        });

        tblTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTabela);

        btnpesqcli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2203511_find_glass_look_magnify_search_icon (1).png"))); // NOI18N
        btnpesqcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesqcliActionPerformed(evt);
            }
        });

        btnpesqSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/430088_circle_close_delete_remove_icon (1).png"))); // NOI18N
        btnpesqSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesqSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioidprod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radiodesdricaoproduto))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addComponent(txtpesqprod))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnpesqcli)
                .addGap(18, 18, 18)
                .addComponent(btnpesqSair)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioidprod)
                    .addComponent(radiodesdricaoproduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtpesqprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpesqcli)
                    .addComponent(btnpesqSair))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpesqSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesqSairActionPerformed
        resposta="";
        dispose();
    }//GEN-LAST:event_btnpesqSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        preencherTabela();
        txtpesqprod.requestFocusInWindow();
    }//GEN-LAST:event_formWindowOpened

    private void radiodesdricaoprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiodesdricaoprodutoActionPerformed
        txtpesqprod.setText("");
        txtpesqprod.requestFocusInWindow();
        preencherTabela();
    }//GEN-LAST:event_radiodesdricaoprodutoActionPerformed

    private void radioidprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioidprodActionPerformed
        txtpesqprod.setText("");
        txtpesqprod.requestFocusInWindow();
        preencherTabela();
    }//GEN-LAST:event_radioidprodActionPerformed

    private void txtpesqprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesqprodActionPerformed
        preencherTabela();
    }//GEN-LAST:event_txtpesqprodActionPerformed

    private void btnpesqcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesqcliActionPerformed
        int num = tblTabela.getRowCount();
        if(num==0){
            resposta="";
            dispose();  
            return;
        }
         for(int i =0; i < num; i++){
            if(tblTabela.isRowSelected(i)){
            resposta = Ultilidades.objectToString(tblTabela.getValueAt(i, 0));
            dispose();  
            return;
            
            }
        }
         resposta = Ultilidades.objectToString(tblTabela.getValueAt(0, 0));
         dispose();  
    }//GEN-LAST:event_btnpesqcliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPesqProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPesqProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPesqProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPesqProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmPesqProdutos dialog = new frmPesqProdutos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgtipopesq;
    private javax.swing.JButton btnpesqSair;
    private javax.swing.JButton btnpesqcli;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radiodesdricaoproduto;
    private javax.swing.JRadioButton radioidprod;
    private javax.swing.JTable tblTabela;
    private javax.swing.JTextField txtpesqprod;
    // End of variables declaration//GEN-END:variables
}
